version: "3.9"

services:
  test-environment:
    build: .
    container_name: port-test-container
    ports:
      - "8080:8080" # Puerto abierto
      - "9090:9090" # Puerto filtrado (bloqueado por iptables)
      - "80:80" # Puerto cerrado (sin servicio)